inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import show_main, create_items, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import increase_amount, decrease_amount, delete
from main.views import edit_item
from main.views import get_item_json, add_item_ajax
from main.views import create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_items, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('item/<int:id>/increase/', increase_amount, name='increase_amount'),
    path('item/<int:id>/decrease/', decrease_amount, name='decrease_amount'),
    path('item/<int:id>/delete/', delete, name='delete'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

shopping_list/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% endblock meta %}
        <link rel="icon" href="{% static 'logo.png' %}" type="image/x-icon">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <style>
            @font-face {
                font-family: 'Default-Font';
                src: url('{% static "fonts/Gogh-ExtraBold.woff" %}') format('woff');
                font-weight: normal;
                font-style: normal;
                color: rgb(132, 119, 106);
            }
            body {
                font-family: 'Default-Font', sans-serif;
                font-weight: bold;
                color: rgb(132, 119, 106);
                background-image: url("{% static 'background-image.png' %}");
                background-size: cover;
                display: flex;
                flex-direction: column;
            }
            .btn-custom {
                background-color: rgb(246, 240, 234);
                color: rgb(132, 119, 106);
            }
            .btn-custom:hover {
                background-color: rgb(132, 119, 106);
                color: rgb(246, 240, 234);
            }
            .navbar-brand {
                color: rgb(132, 119, 106);
                font-size: x-large;
            }
            a.custom-link {
                color: rgb(132, 119, 106);
            }
            a.custom-link:hover, a.custom-link:focus {
                color: rgb(246, 240, 234);
            }
            .content {
                flex: 1;
            }

            .footer {
                flex-shrink: 0;
            }   
        </style>
    </head>

    <body class="d-flex flex-column min-vh-100">
        <nav class="navbar navbar-expand-lg" style="background-color:rgb(246, 240, 234)">
            <div class="container-fluid">
                <a class="navbar-brand">
                    <img src="{% static 'logo.png' %}" alt="Logo" width="60" height="60" class="d-inline-block align-text-center">
                    EURORA'S CLOSET
                </a>
              <a class="btn btn-custom me-2 order-lg-last" type="button" href="{% url 'main:logout' %}">
                Logout
              </a>
            </div>
        </nav>
        <div class="flex-grow-1">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>