inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import show_main, create_items, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import increase_amount, decrease_amount, delete
from main.views import edit_item
from main.views import get_item_json, add_item_ajax
from main.views import create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_items, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('item/<int:id>/increase/', increase_amount, name='increase_amount'),
    path('item/<int:id>/decrease/', decrease_amount, name='decrease_amount'),
    path('item/<int:id>/delete/', delete, name='delete'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

shopping_list/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    CATEGORY_CHOICES = (
        ('Top', 'Top'),
        ('Bottom', 'Bottom'),
        ('Dress', 'Dress'),
        ('Extras', 'Extras'),
        ('Accessories', 'Accessories'),
        ('Footwear', 'Footwear'),
    )

    name = models.CharField(max_length=100)
    amount = models.PositiveIntegerField()
    description = models.TextField()
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, default='top')
    image = models.ImageField(upload_to='items/')

    def cat(self):
        return f"{self.name} is a {self.category}"

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "category", "image"]

main/views.py
import datetime
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)

    last_login = request.COOKIES.get('last_login', 'Not available')    

    context = {
        'app_name': "EURORA'S CLOSET",
        'name': request.user.username,
        'class': 'PBP A',
        'items': items,
        'last_login': last_login,
    }

    return render(request, "main.html", context)

def create_items(request):
    form = ItemForm(request.POST, request.FILES or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return redirect('main:login')

def increase_amount(request, id):
    item = Item.objects.get(pk=id)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrease_amount(request, id):
    item = Item.objects.get(pk=id)
    item.amount -= 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def delete(request, id):
    item = Item.objects.get(pk=id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def edit_item(request, id):
    item = Item.objects.get(pk = id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def get_item_json(request):
    items_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', items_item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        category = request.POST.get("category")
        image = request.FILES.get('image', None)

        new_item = Item(user=user, name=name, amount=amount, description=description, category=category, image=image)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"],
            category = data["category"],
            image = data["image"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh; color: rgb(132, 119, 106);">
    <div class="col-md-6">
        <h1 class="text-center mb-4">Edit Item</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% if field.name == "description" %}
                    <textarea name="{{ field.name }}" id="{{ field.auto_id }}" class="form-control" rows="10">{{ field.value|default:'' }}</textarea>
                {% elif field.name == "category" %}
                <select name="{{ field.name }}" id="{{ field.auto_id }}" class="form-control">
                    {% for value, display_name in field.field.choices %}
                        <option value="{{ value }}" {% if field.value == value %}selected{% endif %} style="color: rgb(132, 119, 106);">{{ display_name }}</option>
                    {% endfor %}
                </select>
                {% elif field.field.widget.input_type == "file" %}
                <label for="{{ field.auto_id }}" class="btn btn-custom">Choose File</label>
                <input type="file" name="{{ field.name }}" id="{{ field.auto_id }}" class="d-none"> 
                <span id="{{ field.auto_id }}-filename" class="ml-2">No file chosen</span>                
                {% else %}
                    <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.auto_id }}" class="form-control" value="{{ field.value|default:'' }}">
                {% endif %}
            </div>
            {% endfor %}
            <div class="form-group text-center mt-3">
                <input type="submit" value="Edit Item" class="btn btn-custom"/>
            </div>
        </form>
        <div class="d-flex justify-content-center align-items-center" style="height: 10vh; padding: 50px;">
            <a class="btn btn-custom" type="button" href="{% url 'main:show_main' %}">
                Back
            </a>
        </div>
    </div>
</div>
<script>
    document.getElementById('{{ field.auto_id }}').addEventListener('change', function() {
        var filePath = this.value;
        var fileNameDisplay = document.getElementById('{{ field.auto_id }}-filename');

        if (filePath) {
            var fileName = filePath.replace(/^.*[\\\/]/, "");  // Extract just the filename from the path
            fileNameDisplay.textContent = fileName;
        } else {
            fileNameDisplay.textContent = "No file chosen";
        }
    });
</script>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
    <style>
        input:focus, textarea:focus, select:focus, button:focus {
            outline: none !important;
            box-shadow: none !important;
        } 
        input:focus, textarea:focus, select:focus, button:focus {
            border-color: rgb(132, 119, 106) !important;
            box-shadow: 0 0 0 0.2rem rgba(132, 119, 106, 0.25) !important;
        }
    </style>
{% endblock meta %}

{% block content %}


<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="login w-50">

        <div class="text-center mb-4">
            <h2>Welcome!</h2>
            <p>Please enter your credentials to access your account.</p>
        </div>

        <form method="POST" action="" class="p-4 border rounded" style="background-color: white;">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" name="username" placeholder="Username" class="form-control" id="username">
            </div>
            
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" placeholder="Password" class="form-control" id="password">
            </div>

            <div class="text-center">
                <input class="btn btn-custom login_btn" type="submit" value="Login">
            </div>

        </form>

        {% if messages %}
            <div class="mt-3">
                <ul class="alert alert-danger">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}     

        <div class="text-center mt-3">
            Don't have an account yet? <a href="{% url 'main:register' %}" class="custom-link">Register Now</a>
        </div>

    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<head>
    <style>
        .card-container .card:last-child, .last-item-card .card {
            background-color: rgb(73, 67, 62); /* contoh warna merah muda */
        }
    </style>
</head>
<body>
    <div class="container text-center mt-5">
        <h2>Hi, {{ name }}!</h2>
        <p>You have {{ items|length }} items in your closet.</p>
    
        <div class="my-4">
            <a href="{% url 'main:create_item' %}" class="btn btn-custom btn-lg">
                Add New Item
            </a>
        </div>
        <button type="button" class="btn btn-custom" data-bs-toggle="modal" data-bs-target="#addItemModal">Add Item by AJAX</button>
    </div>

    <div class="container">
        <div class="row" id="items_container">
            Total items: {{ items|length }}
            {% for item in items %}
            <div class="col-md-4 mb-4">
                <div class="card {% if forloop.last %}last-item-card{% endif %}">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text">
                            <strong>Amount:</strong> {{ item.amount }}<br>
                            <strong>Description:</strong> {{ item.description }}<br>
                            <strong>Category:</strong> {{ item.category }}<br>
                        </p>
                        <a href="{% url 'main:edit_item' item.pk %}" class="btn btn-custom">Edit</a>
                        <a href="{% url 'main:delete' item.pk %}" onclick="return confirm('Are you sure?');" class="btn btn-custom">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}        
        </div>
    </div>

    <div class="modal fade" id="addItemModal" tabindex="-1" aria-labelledby="addItemModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addItemModalLabel">Add New Item</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="addItemForm">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="itemName" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="itemName" name="name">
                        </div>
                        <div class="mb-3">
                            <label for="itemAmount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="itemAmount" name="amount">
                        </div>
                        <div class="mb-3">
                            <label for="itemDescription" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="itemDescription" name="description"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="itemCategory" class="col-form-label">Category:</label>
                            <select class="form-control" id="itemCategory" name="category">
                                <option value="Top">Top</option>
                                <option value="Bottom">Bottom</option>
                                <option value="Dress">Dress</option>
                                <option value="Extras">Extras</option>
                                <option value="Accessories">Accessories</option>
                                <option value="Footwear">Footwear</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="itemImage" class="col-form-label">Image:</label>
                            <input type="file" class="form-control" id="itemImage" name="image">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="saveItemButton">Save Item</button>
                </div>
            </div>
        </div>
    </div>

    
    <footer class="footer" style="background-color: rgb(246, 240, 234);">
        <div class="container text-center">
            <p>Sesi terakhir login: {{ last_login }}</p>
        </div>
    </footer>
    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json());
        }
        async function refreshItems() {
            document.getElementById("items_container").innerHTML = "";
            const items = await getItems();

            let htmlString = '';
            items.forEach((item) => {
                htmlString += `
                <div class="card" style="width: 18rem;">
                    <img src="${item.fields.image}" class="card-img-top" alt="${item.fields.name}">
                    <div class="card-body">
                        <h5 class="card-title">${item.fields.name}</h5>
                        <p class="card-text">${item.fields.description}</p>
                        <p class="card-text">Amount: ${item.fields.amount}</p>
                        <p class="card-text">Category: ${item.fields.category}</p>
                    </div>
                </div>`;
            });

            document.getElementById("items_container").innerHTML = htmlString;
        }
        refreshItems();
        function addItem() {
            const formData = new FormData(document.querySelector('#addItemForm'));
            formData.append('csrfmiddlewaretoken', document.querySelector('[name=csrfmiddlewaretoken]').value);
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: formData
            }).then(response => {
                if (response.ok) {
                    return response.text();
                } else {
                    throw new Error('Failed to add item.');
                }
            }).then(data => {
                if (data === "CREATED") {
                    refreshItems();
                }
            }).catch(error => {
                console.error('Error:', error);
            });

            document.getElementById("addItemForm").reset();
            return false;
        }
        document.getElementById("saveItemButton").addEventListener("click", addItem);
    </script>
</body>
</html>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
    <style>
    input, textarea, select, label {
        color: rgb(132, 119, 106) !important;
    }
    .rounded-field {
        border-radius: 15px;
    }
    </style>
{% endblock meta %}

{% block content %}  

<div class="d-flex justify-content-center align-items-center" style="height: 100vh; color: rgb(132, 119, 106);">
    <div class="register w-50">
        <h1 class="text-center mb-4">Register</h1>

        <form method="POST" action="" class="p-4 border rounded" style="background-color: white;">
            {% csrf_token %}
            <table class="table table-borderless">
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input class="btn btn-custom" type="submit" name="submit" value="Register"/></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <div class="mt-3">
                <ul class="alert" style="background-color: rgb(132, 119, 106); font-size: 0.8rem; color: rgb(246, 240, 234);"> <!-- Warna "coklat" diganti menjadi "brown" -->
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    
        
    </div>
</div>  

{% endblock content %}